# Generated by Django 5.0.1 on 2024-02-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variation_value',
            new_name='color',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='variation_category',
        ),
        migrations.AddField(
            model_name='variation',
            name='size',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
