# Generated by Django 5.0.1 on 2024-03-04 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_order_phone'),
        ('cart', '0005_remove_cart_item_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.cart_item'),
            preserve_default=False,
        ),
    ]
