# Generated by Django 5.0.1 on 2024-01-26 18:01

import category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to=category.models.image_upload),
        ),
    ]
