# Generated by Django 5.0.1 on 2024-02-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_item_cart_cart_item_user'),
        ('store', '0004_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
