# Generated by Django 5.0.1 on 2024-02-23 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_variation_cart_item_user_cart_item_variations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item',
            name='cart',
        ),
    ]
