# Generated by Django 5.0.1 on 2024-03-01 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_item_cart_cart_item_user_and_more'),
        ('store', '0004_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='vartions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.variation'),
        ),
    ]
