# Generated by Django 5.0.1 on 2024-02-25 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_item_user_cart_item_variations'),
        ('store', '0005_rename_variation_value_variation_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item',
            name='variations',
        ),
        migrations.AddField(
            model_name='cart_item',
            name='variations',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='store.variation'),
            preserve_default=False,
        ),
    ]
