# Generated by Django 5.0.1 on 2024-02-23 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_item_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='variations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.variation'),
        ),
    ]
